component_depth: 1
languages:
- java
exclude:
- ./bin/.*
- ./bin/META-INF/.*
- ./bin/com/.*
- ./bin/com/meterware/.*
- ./bin/com/meterware/servletunit/.*
- ./bin/org/.*
- ./bin/org/apache/.*
- ./bin/org/apache/jasper/.*
- ./bin/org/apache/jasper/runtime/.*
- ./bin/org/apache/jasper/servlet/.*
- ./bin/org/displaytag/.*
- ./bin/org/displaytag/decorator/.*
- ./bin/org/displaytag/decorator/hssf/.*
- ./bin/org/displaytag/exception/.*
- ./bin/org/displaytag/export/.*
- ./bin/org/displaytag/export/excel/.*
- ./bin/org/displaytag/filter/.*
- ./bin/org/displaytag/jsptests/.*
- ./bin/org/displaytag/localization/.*
- ./bin/org/displaytag/model/.*
- ./bin/org/displaytag/pagination/.*
- ./bin/org/displaytag/portlet/.*
- ./bin/org/displaytag/properties/.*
- ./bin/org/displaytag/render/.*
- ./bin/org/displaytag/sample/.*
- ./bin/org/displaytag/sample/decorators/.*
- ./bin/org/displaytag/tags/.*
- ./bin/org/displaytag/tags/el/.*
- ./bin/org/displaytag/test/.*
- ./bin/org/displaytag/tld/.*
- ./bin/org/displaytag/util/.*
- ./displaytag/.*
- ./displaytag-examples/.*
- ./displaytag-export-poi/.*
- ./displaytag-portlet/.*
- ./lib/.*
